import type { Database } from "./database.types";

export type Quiz = Omit<Database["public"]["Tables"]["quizzes"]["Row"], "category"> & {
  category: string;
};
type Question = Database["public"]["Tables"]["questions"]["Row"];

export interface PathQuizBundle {
  quiz: Quiz;
  questions: Question[];
}

/**
 * Catalogue complet des quiz officiels intégrés pour chaque niveau du Parcours d'Apprentissage.
 * Permet aux joueurs de progresser directement à travers des défis géographiques captivants.
 */
export const PATH_QUIZZES: Record<string, PathQuizBundle> = {
  // ── UNITÉ 1 : Continents & Merveilles ─────────────────────────────────
  "u1-n1": {
    quiz: {
      id: "u1-n1",
      creator_id: "system-path",
      title: "Les 7 Continents de la Terre",
      description: "Défie tes connaissances sur la forme, la taille et les particularités des 7 continents.",
      category: "regions",
      is_public: true,
      is_global: true,
      difficulty: "easy",
      time_limit_seconds: 30,
      total_plays: 1420,
      average_score: 82,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["continents", "terre", "globe", "parcours"],
    },
    questions: [
      {
        id: "u1-n1-q1",
        quiz_id: "u1-n1",
        question_text: "Quel est le plus grand continent du monde en termes de superficie terrestre ?",
        question_type: "mcq",
        correct_answer: "L'Asie",
        correct_answers: null,
        options: ["L'Asie", "L'Afrique", "L'Amérique du Nord", "L'Europe"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Asie couvre plus de 44 millions de km², soit environ 30% des terres émergées de la planète.",
      },
      {
        id: "u1-n1-q2",
        quiz_id: "u1-n1",
        question_text: "Sur quel continent ne trouve-t-on aucune population résidente permanente ni aucun pays souverain ?",
        question_type: "mcq",
        correct_answer: "L'Antarctique",
        correct_answers: null,
        options: ["L'Antarctique", "L'Océanie", "L'Afrique", "L'Amérique du Sud"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Antarctique est régi par le Traité sur l'Antarctique et n'accueille que des missions scientifiques temporaires.",
      },
      {
        id: "u1-n1-q3",
        quiz_id: "u1-n1",
        question_text: "Quel continent est surnommé le « Berceau de l'Humanité » ?",
        question_type: "mcq",
        correct_answer: "L'Afrique",
        correct_answers: null,
        options: ["L'Afrique", "L'Asie", "L'Europe", "L'Océanie"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "C'est en Afrique de l'Est que les plus anciens fossiles d'hominidés ont été découverts.",
      },
      {
        id: "u1-n1-q4",
        quiz_id: "u1-n1",
        question_text: "Quel est le plus petit continent du monde en superficie terrestre ?",
        question_type: "mcq",
        correct_answer: "L'Océanie",
        correct_answers: null,
        options: ["L'Océanie", "L'Europe", "L'Amérique du Sud", "L'Antarctique"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Océanie couvre environ 8,5 millions de km², dont l'Australie représente la très grande majorité.",
      },
      {
        id: "u1-n1-q5",
        quiz_id: "u1-n1",
        question_text: "Quelle chaîne de montagnes marque traditionnellement la frontière naturelle entre l'Europe et l'Asie ?",
        question_type: "mcq",
        correct_answer: "L'Oural",
        correct_answers: null,
        options: ["L'Oural", "L'Himalaya", "Les Alpes", "Le Caucase"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Les monts Oural s'étendent du nord au sud de la Russie sur plus de 2 500 km.",
      },
    ],
  },

  "u1-n2": {
    quiz: {
      id: "u1-n2",
      creator_id: "system-path",
      title: "Océans & Grandes Mers du Monde",
      description: "Plonge au cœur des abysses : océans géants, fosses marines et mers mythiques.",
      category: "regions",
      is_public: true,
      is_global: true,
      difficulty: "easy",
      time_limit_seconds: 30,
      total_plays: 980,
      average_score: 79,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["oceans", "mers", "mer", "parcours"],
    },
    questions: [
      {
        id: "u1-n2-q1",
        quiz_id: "u1-n2",
        question_text: "Quel est le plus grand et le plus profond des océans du globe terrestre ?",
        question_type: "mcq",
        correct_answer: "L'océan Pacifique",
        correct_answers: null,
        options: ["L'océan Pacifique", "L'océan Atlantique", "L'océan Indien", "L'océan Arctique"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'océan Pacifique couvre à lui seul plus d'un tiers de la surface terrestre totale.",
      },
      {
        id: "u1-n2-q2",
        quiz_id: "u1-n2",
        question_text: "Dans quel océan se situe la fosse des Mariannes, le point le plus profond connu sur Terre (~11 000 m) ?",
        question_type: "mcq",
        correct_answer: "L'océan Pacifique",
        correct_answers: null,
        options: ["L'océan Pacifique", "L'océan Indien", "L'océan Atlantique", "L'océan Austral"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La fosse des Mariannes abrite le gouffre Challenger à près de 11 kilomètres sous le niveau de la mer.",
      },
      {
        id: "u1-n2-q3",
        quiz_id: "u1-n2",
        question_text: "Quel détroit sépare la péninsule ibérique du continent africain ?",
        question_type: "mcq",
        correct_answer: "Le détroit de Gibraltar",
        correct_answers: null,
        options: ["Le détroit de Gibraltar", "Le détroit du Bosphore", "Le détroit de Béring", "Le détroit de Malacca"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le détroit de Gibraltar ne fait que 14 kilomètres de large à son point le plus resserré.",
      },
      {
        id: "u1-n2-q4",
        quiz_id: "u1-n2",
        question_text: "Quelle mer fermée hypersalée possède la rive la plus basse à la surface du globe (-430 m) ?",
        question_type: "mcq",
        correct_answer: "La mer Morte",
        correct_answers: null,
        options: ["La mer Morte", "La mer Caspienne", "La mer Rouge", "La mer Baltique"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La mer Morte est si salée qu'aucun poisson n'y survit et que les corps humains y flottent naturellement sans effort.",
      },
      {
        id: "u1-n2-q5",
        quiz_id: "u1-n2",
        question_text: "Quel océan entoure entièrement le continent Antarctique au pôle Sud ?",
        question_type: "mcq",
        correct_answer: "L'océan Austral",
        correct_answers: null,
        options: ["L'océan Austral", "L'océan Indien", "L'océan Pacifique", "L'océan Arctique"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'océan Austral (ou océan Antarctique) est officiellement reconnu sous le 60e parallèle sud.",
      },
    ],
  },

  "u1-n3": {
    quiz: {
      id: "u1-n3",
      creator_id: "system-path",
      title: "Merveilles Naturelles de la Terre",
      description: "Grand Canyon, Chutes d'Iguazú, Barrière de Corail : teste ta culture des paysages du monde.",
      category: "mixed",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 850,
      average_score: 76,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["merveilles", "nature", "paysages", "parcours"],
    },
    questions: [
      {
        id: "u1-n3-q1",
        quiz_id: "u1-n3",
        question_text: "Dans quel pays se trouve le Salar d'Uyuni, le plus vaste désert de sel du monde ?",
        question_type: "mcq",
        correct_answer: "La Bolivie",
        correct_answers: null,
        options: ["La Bolivie", "Le Chili", "L'Argentine", "Le Pérou"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Salar d'Uyuni s'étend sur plus de 10 500 km² à plus de 3 600 mètres d'altitude.",
      },
      {
        id: "u1-n3-q2",
        quiz_id: "u1-n3",
        question_text: "Le fleuve Colorado a sculpté au fil des millénaires quelle gorge spectaculaire aux États-Unis ?",
        question_type: "mcq",
        correct_answer: "Le Grand Canyon",
        correct_answers: null,
        options: ["Le Grand Canyon", "Le Monument Valley", "Le Yosemite Valley", "Le Bryce Canyon"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Grand Canyon en Arizona mesure 450 km de long et atteint jusqu'à 1 800 mètres de profondeur.",
      },
      {
        id: "u1-n3-q3",
        quiz_id: "u1-n3",
        question_text: "Au large de quel pays s'étend la Grande Barrière de Corail, visible depuis l'espace ?",
        question_type: "mcq",
        correct_answer: "L'Australie",
        correct_answers: null,
        options: ["L'Australie", "La Nouvelle-Zélande", "L'Indonésie", "Les Philippines"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La Grande Barrière s'étend sur plus de 2 300 kilomètres au large de l'État du Queensland.",
      },
      {
        id: "u1-n3-q4",
        quiz_id: "u1-n3",
        question_text: "Les spectaculaires chutes Victoria se situent sur le fleuve Zambèze, entre la Zambie et quel autre pays ?",
        question_type: "mcq",
        correct_answer: "Le Zimbabwe",
        correct_answers: null,
        options: ["Le Zimbabwe", "Le Botswana", "La Namibie", "Le Mozambique"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Connues sous le nom indigène de « Mosi-oa-Tunya » (La fumée qui gronde), elles déversent des millions de litres par seconde.",
      },
      {
        id: "u1-n3-q5",
        quiz_id: "u1-n3",
        question_text: "Quelle montagne volcanique sacrée est le point culminant du Japon (3 776 m) ?",
        question_type: "mcq",
        correct_answer: "Le mont Fuji",
        correct_answers: null,
        options: ["Le mont Fuji", "Le mont Aso", "Le mont Tate", "Le mont Haku"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le mont Fuji est un volcan endormi dont la silhouette conique parfaite est un symbole national du Japon.",
      },
    ],
  },

  "u1-boss": {
    quiz: {
      id: "u1-boss",
      creator_id: "system-path",
      title: "👑 Boss de l'Unité 1 : Le Maître du Globe",
      description: "Prouve ta maîtrise absolue des continents, océans et merveilles de notre planète !",
      category: "mixed",
      is_public: true,
      is_global: true,
      difficulty: "hard",
      time_limit_seconds: 25,
      total_plays: 620,
      average_score: 71,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["boss", "monde", "continents", "parcours"],
    },
    questions: [
      {
        id: "u1-b-q1",
        quiz_id: "u1-boss",
        question_text: "Quel pays s'étend à la fois sur le continent européen et sur le continent asiatique ?",
        question_type: "mcq",
        correct_answer: "La Turquie",
        correct_answers: null,
        options: ["La Turquie", "L'Iran", "L'Ukraine", "La Grèce"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Istanbul est la seule mégapole au monde à cheval sur deux continents, séparée par le Bosphore.",
      },
      {
        id: "u1-b-q2",
        quiz_id: "u1-boss",
        question_text: "Quel est le lac d'eau douce le plus ancien et le plus profond du monde (1 642 m) ?",
        question_type: "mcq",
        correct_answer: "Le lac Baïkal",
        correct_answers: null,
        options: ["Le lac Baïkal", "Le lac Supérieur", "Le lac Tanganyika", "Le lac Victoria"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Situé en Sibérie, le lac Baïkal renferme environ 20% de toute l'eau douce de surface non gelée du monde.",
      },
      {
        id: "u1-b-q3",
        quiz_id: "u1-boss",
        question_text: "L'isthme de Panama relie l'Amérique du Nord à quel continent ?",
        question_type: "mcq",
        correct_answer: "L'Amérique du Sud",
        correct_answers: null,
        options: ["L'Amérique du Sud", "L'Afrique", "L'Asie", "L'Océanie"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le canal de Panama a été percé à travers cet isthme pour relier l'océan Atlantique et l'océan Pacifique.",
      },
      {
        id: "u1-b-q4",
        quiz_id: "u1-boss",
        question_text: "Quel pays possède le littoral maritime le plus long du monde (plus de 202 000 km) ?",
        question_type: "mcq",
        correct_answer: "Le Canada",
        correct_answers: null,
        options: ["Le Canada", "La Russie", "L'Indonésie", "L'Australie"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Grâce à ses milliers d'îles arctiques et ses baies découpées, le Canada possède la plus longue côte du globe.",
      },
      {
        id: "u1-b-q5",
        quiz_id: "u1-boss",
        question_text: "Quel point cardinal correspond aux coordonnées 0° de latitude et 0° de longitude dans le golfe de Guinée ?",
        question_type: "mcq",
        correct_answer: "L'intersection de l'Équateur et du méridien de Greenwich",
        correct_answers: null,
        options: [
          "L'intersection de l'Équateur et du méridien de Greenwich",
          "Le Pôle Nord magnétique",
          "Le tropique du Cancer",
          "Le Cap de Bonne-Espérance",
        ],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le point (0, 0), parfois surnommé « Null Island », est le croisement de l'Équateur et du méridien zéro.",
      },
    ],
  },

  // ── UNITÉ 2 : Capitales & Joyaux d'Europe ──────────────────────────────
  "u2-n1": {
    quiz: {
      id: "u2-n1",
      creator_id: "system-path",
      title: "Capitales d'Europe de l'Ouest",
      description: "Parcours les grandes métropoles européennes et retrouve leurs capitales.",
      category: "capitals",
      is_public: true,
      is_global: true,
      difficulty: "easy",
      time_limit_seconds: 30,
      total_plays: 1100,
      average_score: 85,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["capitales", "europe", "villes", "parcours"],
    },
    questions: [
      {
        id: "u2-n1-q1",
        quiz_id: "u2-n1",
        question_text: "Quelle est la capitale officielle de la Suisse (ville fédérale) ?",
        question_type: "mcq",
        correct_answer: "Berne",
        correct_answers: null,
        options: ["Berne", "Genève", "Zurich", "Bâle"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Berne abrite le Palais fédéral et le siège du Conseil fédéral suisse depuis 1848.",
      },
      {
        id: "u2-n1-q2",
        quiz_id: "u2-n1",
        question_text: "Quelle capitale européenne est traversée par le Tage ?",
        question_type: "mcq",
        correct_answer: "Lisbonne",
        correct_answers: null,
        options: ["Lisbonne", "Madrid", "Séville", "Porto"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Tage se jette dans l'océan Atlantique à Lisbonne, formant une baie spectaculaire.",
      },
      {
        id: "u2-n1-q3",
        quiz_id: "u2-n1",
        question_text: "Quelle est la capitale des Pays-Bas (bien que le gouvernement siège à La Haye) ?",
        question_type: "mcq",
        correct_answer: "Amsterdam",
        correct_answers: null,
        options: ["Amsterdam", "Rotterdam", "Utrecht", "Eindhoven"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Amsterdam est la capitale constitutionnelle, réputée pour ses canaux et son architecture du Siècle d'or.",
      },
      {
        id: "u2-n1-q4",
        quiz_id: "u2-n1",
        question_text: "Quelle est la capitale de l'Autriche, ville impériale baignée par le Danube ?",
        question_type: "mcq",
        correct_answer: "Vienne",
        correct_answers: null,
        options: ["Vienne", "Salzbourg", "Innsbruck", "Graz"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Vienne fut le cœur de l'Empire austro-hongrois et la patrie de nombreux compositeurs célèbres comme Mozart et Beethoven.",
      },
      {
        id: "u2-n1-q5",
        quiz_id: "u2-n1",
        question_text: "Quelle ville est à la fois la capitale de l'Union européenne et de la Belgique ?",
        question_type: "mcq",
        correct_answer: "Bruxelles",
        correct_answers: null,
        options: ["Bruxelles", "Strasbourg", "Luxembourg", "Anvers"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Bruxelles abrite la Commission européenne, le Conseil de l'Union européenne et l'OTAN.",
      },
    ],
  },

  "u2-n2": {
    quiz: {
      id: "u2-n2",
      creator_id: "system-path",
      title: "Monuments & Patrimoine d'Europe",
      description: "Colisée, Sagrada Familia, Parthénon : explore les joyaux d'architecture de l'histoire européenne.",
      category: "mixed",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 740,
      average_score: 80,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["monuments", "europe", "histoire", "parcours"],
    },
    questions: [
      {
        id: "u2-n2-q1",
        quiz_id: "u2-n2",
        question_text: "Dans quelle ville espagnole se dresse la majestueuse basilique de la Sagrada Família, œuvre d'Antoni Gaudí ?",
        question_type: "mcq",
        correct_answer: "Barcelone",
        correct_answers: null,
        options: ["Barcelone", "Madrid", "Valence", "Séville"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La construction de la Sagrada Família a débuté en 1882 et se poursuit encore aujourd'hui.",
      },
      {
        id: "u2-n2-q2",
        quiz_id: "u2-n2",
        question_text: "Sur quelle colline fortifiée d'Athènes trône le Parthénon dédié à la déesse Athéna ?",
        question_type: "mcq",
        correct_answer: "L'Acropole",
        correct_answers: null,
        options: ["L'Acropole", "Le mont Lycabette", "Le mont Olympe", "Le Capitole"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Acropole d'Athènes domine la capitale grecque depuis le Ve siècle avant J.-C.",
      },
      {
        id: "u2-n2-q3",
        quiz_id: "u2-n2",
        question_text: "L'Alhambra, chef-d'œuvre de l'architecture islamique en Europe, se situe dans quelle ville d'Andalousie ?",
        question_type: "mcq",
        correct_answer: "Grenade",
        correct_answers: null,
        options: ["Grenade", "Cordoue", "Málaga", "Tolède"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Alhambra de Grenade est l'un des monuments les plus visités d'Espagne et classé à l'UNESCO.",
      },
      {
        id: "u2-n2-q4",
        quiz_id: "u2-n2",
        question_text: "Quel château médiéval suisse est célèbre pour border le lac Léman près de Montreux ?",
        question_type: "mcq",
        correct_answer: "Le château de Chillon",
        correct_answers: null,
        options: ["Le château de Chillon", "Le château de Gruyères", "Le château d'Aigle", "Le château de Grandson"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le château de Chillon a inspiré Lord Byron pour son poème 'Le Prisonnier de Chillon'.",
      },
      {
        id: "u2-n2-q5",
        quiz_id: "u2-n2",
        question_text: "Dans quel pays peut-on admirer les célèbres moulins de Kinderdijk, symboles de la maîtrise de l'eau ?",
        question_type: "mcq",
        correct_answer: "Les Pays-Bas",
        correct_answers: null,
        options: ["Les Pays-Bas", "Le Danemark", "La Belgique", "L'Allemagne"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Les 19 moulins à vent de Kinderdijk servaient autrefois à drainer les polders sous le niveau de la mer.",
      },
    ],
  },

  "u2-n3": {
    quiz: {
      id: "u2-n3",
      creator_id: "system-path",
      title: "Drapeaux & Symboles d'Europe",
      description: "Croix scandinaves, bandes tricolores et aigles royaux : maîtrise les drapeaux européens.",
      category: "flags",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 25,
      total_plays: 890,
      average_score: 83,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["drapeaux", "flags", "europe", "parcours"],
    },
    questions: [
      {
        id: "u2-n3-q1",
        quiz_id: "u2-n3",
        question_text: "Quel est le seul drapeau national en Europe (avec le Vatican) à posséder une forme carrée ?",
        question_type: "mcq",
        correct_answer: "La Suisse",
        correct_answers: null,
        options: ["La Suisse", "La Norvège", "L'Islande", "Monaco"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le drapeau suisse officiel arbore une croix blanche sur fond rouge dans un format parfaitement carré 1:1.",
      },
      {
        id: "u2-n3-q2",
        quiz_id: "u2-n3",
        question_text: "Quel pays scandinave possède le plus ancien drapeau national encore utilisé sans interruption (Dannebrog) ?",
        question_type: "mcq",
        correct_answer: "Le Danemark",
        correct_answers: null,
        options: ["Le Danemark", "La Suède", "La Norvège", "La Finlande"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le drapeau danois remonte à 1219 selon la légende de la bataille de Lyndanisse.",
      },
      {
        id: "u2-n3-q3",
        quiz_id: "u2-n3",
        question_text: "Quelles sont les trois couleurs horizontales du drapeau de l'Allemagne (de haut en bas) ?",
        question_type: "mcq",
        correct_answer: "Noir, Rouge, Or",
        correct_answers: null,
        options: ["Noir, Rouge, Or", "Rouge, Blanc, Noir", "Or, Rouge, Noir", "Bleu, Blanc, Rouge"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Les couleurs Schwarz-Rot-Gold proviennent des uniformes du corps franc de Lützow lors des guerres napoléoniennes.",
      },
      {
        id: "u2-n3-q4",
        quiz_id: "u2-n3",
        question_text: "Quel pays d'Europe arbore une harpe celtique d'or comme emblème officiel (aussi sur ses pièces d'euro) ?",
        question_type: "mcq",
        correct_answer: "L'Irlande",
        correct_answers: null,
        options: ["L'Irlande", "L'Écosse", "Le Pays de Galles", "La Bretagne"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La harpe de Brian Boru est l'emblème national de la République d'Irlande.",
      },
      {
        id: "u2-n3-q5",
        quiz_id: "u2-n3",
        question_text: "Le drapeau de la Grèce compte 9 bandes horizontales bleues et blanches représentant quoi ?",
        question_type: "mcq",
        correct_answer: "Les 9 syllabes de la devise « La liberté ou la mort »",
        correct_answers: null,
        options: [
          "Les 9 syllabes de la devise « La liberté ou la mort »",
          "Les 9 mers entourant les îles grecques",
          "Les 9 dieux de l'Olympe",
          "Les 9 régions antiques de Grèce",
        ],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "« Elefthería í thánatos » (Liberté ou mort) compte exactement neuf syllabes en grec.",
      },
    ],
  },

  "u2-boss": {
    quiz: {
      id: "u2-boss",
      creator_id: "system-path",
      title: "👑 Boss de l'Unité 2 : Empereur Européen",
      description: "Le grand défi récapitulatif des 44 nations du continent européen.",
      category: "mixed",
      is_public: true,
      is_global: true,
      difficulty: "hard",
      time_limit_seconds: 25,
      total_plays: 510,
      average_score: 69,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["boss", "europe", "champion", "parcours"],
    },
    questions: [
      {
        id: "u2-b-q1",
        quiz_id: "u2-boss",
        question_text: "Quel petit État souverain est entièrement enclavé à l'intérieur de la ville de Rome ?",
        question_type: "mcq",
        correct_answer: "Le Vatican",
        correct_answers: null,
        options: ["Le Vatican", "Saint-Marin", "Monaco", "Le Liechtenstein"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La Cité du Vatican a une superficie de seulement 0,49 km², ce qui en fait le plus petit État indépendant du monde.",
      },
      {
        id: "u2-b-q2",
        quiz_id: "u2-boss",
        question_text: "Quel est le plus long fleuve d'Europe (environ 3 530 km), se jetant dans la mer Caspienne ?",
        question_type: "mcq",
        correct_answer: "La Volga",
        correct_answers: null,
        options: ["La Volga", "Le Danube", "Le Rhin", "Le Dniepr"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La Volga coule intégralement en Russie occidentale et est affectueusement surnommée « Mère Volga ».",
      },
      {
        id: "u2-b-q3",
        quiz_id: "u2-boss",
        question_text: "Quelle principauté alpine située entre la Suisse et l'Autriche a pour capitale Vaduz ?",
        question_type: "mcq",
        correct_answer: "Le Liechtenstein",
        correct_answers: null,
        options: ["Le Liechtenstein", "Andorre", "Le Luxembourg", "Saint-Marin"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Liechtenstein est l'un des deux seuls pays au monde doublement enclavé (sans accès à la mer, entouré de pays sans accès à la mer).",
      },
      {
        id: "u2-b-q4",
        quiz_id: "u2-boss",
        question_text: "Quel pays d'Europe du Nord compte plus de 180 000 lacs sur son territoire (le pays des mille lacs) ?",
        question_type: "mcq",
        correct_answer: "La Finlande",
        correct_answers: null,
        options: ["La Finlande", "La Suède", "L'Estonie", "L'Islande"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 15,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La Finlande compte exactement 187 888 lacs de plus de 500 m² !",
      },
      {
        id: "u2-b-q5",
        quiz_id: "u2-boss",
        question_text: "Quelle capitale européenne est la plus septentrionale (située le plus au nord de la planète) ?",
        question_type: "mcq",
        correct_answer: "Reykjavik (Islande)",
        correct_answers: null,
        options: ["Reykjavik (Islande)", "Oslo (Norvège)", "Helsinki (Finlande)", "Stockholm (Suède)"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Reykjavik se trouve à 64°08' de latitude Nord, très près du cercle polaire arctique.",
      },
    ],
  },

  // ── UNITÉ 3 : Fleuves, Sommets & Déserts Sauvages ────────────────────
  "u3-n1": {
    quiz: {
      id: "u3-n1",
      creator_id: "system-path",
      title: "Les Grands Fleuves du Monde",
      description: "Navigue le long des plus puissants cours d'eau de la planète.",
      category: "rivers",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 860,
      average_score: 76,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["fleuves", "rivieres", "eau", "parcours"],
    },
    questions: [
      {
        id: "u3-n1-q1",
        quiz_id: "u3-n1",
        question_text: "Quel fleuve possède le plus grand débit d'eau au monde ?",
        question_type: "mcq",
        correct_answer: "L'Amazone",
        correct_answers: null,
        options: ["L'Amazone", "Le Nil", "Le Mississippi", "Le Yangtsé"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Amazone déverse en moyenne 209 000 m³ d'eau par seconde dans l'Atlantique, plus que les 7 fleuves suivants réunis.",
      },
      {
        id: "u3-n1-q2",
        quiz_id: "u3-n1",
        question_text: "Dans quel pays le Nil se jette-t-il dans la mer Méditerranée en formant un vaste delta ?",
        question_type: "mcq",
        correct_answer: "L'Égypte",
        correct_answers: null,
        options: ["L'Égypte", "Le Soudan", "L'Éthiopie", "L'Ouganda"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le delta du Nil au nord de l'Égypte est l'une des régions agricoles les plus fertiles et peuplées au monde.",
      },
      {
        id: "u3-n1-q3",
        quiz_id: "u3-n1",
        question_text: "Quel est le plus long fleuve d'Asie, traversant uniquement la Chine (6 300 km) ?",
        question_type: "mcq",
        correct_answer: "Le Yangtsé (Fleuve Bleu)",
        correct_answers: null,
        options: ["Le Yangtsé (Fleuve Bleu)", "Le Fleuve Jaune", "Le Mékong", "Le Gange"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Yangtsé accueille le barrage des Trois-Gorges, la plus grande centrale hydroélectrique du monde.",
      },
      {
        id: "u3-n1-q4",
        quiz_id: "u3-n1",
        question_text: "Combien de pays européens le fleuve Danube traverse-t-il ou longe-t-il ?",
        question_type: "mcq",
        correct_answer: "10 pays",
        correct_answers: null,
        options: ["10 pays", "6 pays", "4 pays", "14 pays"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Danube prend sa source en Allemagne et traverse l'Autriche, la Slovaquie, la Hongrie, la Croatie, la Serbie, la Bulgarie, la Roumanie, la Moldavie et l'Ukraine.",
      },
      {
        id: "u3-n1-q5",
        quiz_id: "u3-n1",
        question_text: "Dans quel plan d'eau se jette le fleuve Mississippi après avoir traversé les États-Unis ?",
        question_type: "mcq",
        correct_answer: "Le golfe du Mexique",
        correct_answers: null,
        options: ["Le golfe du Mexique", "L'océan Atlantique", "La baie d'Hudson", "L'océan Pacifique"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Mississippi forme son delta en Louisiane au sud de La Nouvelle-Orléans avant de rejoindre le golfe du Mexique.",
      },
    ],
  },

  "u3-n2": {
    quiz: {
      id: "u3-n2",
      creator_id: "system-path",
      title: "Les Toits du Monde",
      description: "Défie les sommets et les grandes chaînes de montagnes.",
      category: "mountains",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 720,
      average_score: 72,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["montagnes", "sommets", "relief", "parcours"],
    },
    questions: [
      {
        id: "u3-n2-q1",
        quiz_id: "u3-n2",
        question_text: "Dans quelle chaîne de montagnes se trouve le mont Everest (8 849 m) ?",
        question_type: "mcq",
        correct_answer: "L'Himalaya",
        correct_answers: null,
        options: ["L'Himalaya", "Les Andes", "Les Alpes", "Le Caucase"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Everest chevauche la frontière entre le Népal et la région autonome du Tibet en Chine.",
      },
      {
        id: "u3-n2-q2",
        quiz_id: "u3-n2",
        question_text: "Quel est le point culminant de la chaîne des Andes et de tout le continent américain (6 961 m) ?",
        question_type: "mcq",
        correct_answer: "L'Aconcagua",
        correct_answers: null,
        options: ["L'Aconcagua", "Le Chimborazo", "Le Huascarán", "L'Ojos del Salado"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Aconcagua est situé en Argentine, près de la frontière avec le Chili.",
      },
      {
        id: "u3-n2-q3",
        quiz_id: "u3-n2",
        question_text: "Quel est le plus haut sommet d'Europe occidentale (4 808 m) ?",
        question_type: "mcq",
        correct_answer: "Le Mont Blanc",
        correct_answers: null,
        options: ["Le Mont Blanc", "Le Cervin", "L'Elbrouz", "La Jungfrau"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Mont Blanc culmine dans le massif des Alpes entre la France et l'Italie.",
      },
      {
        id: "u3-n2-q4",
        quiz_id: "u3-n2",
        question_text: "Quel est le deuxième sommet le plus haut de la Terre (8 611 m), réputé extrêmement difficile et situé dans le Karakoram ?",
        question_type: "mcq",
        correct_answer: "Le K2",
        correct_answers: null,
        options: ["Le K2", "Le Kangchenjunga", "Le Lhotse", "Le Makalu"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le K2 se situe entre le Pakistan et la Chine. Il est surnommé la montagne sauvage en raison de son taux élevé de mortalité.",
      },
      {
        id: "u3-n2-q5",
        quiz_id: "u3-n2",
        question_text: "Sur quel continent se dresse le mont Kilimandjaro, point culminant à 5 895 mètres ?",
        question_type: "mcq",
        correct_answer: "L'Afrique",
        correct_answers: null,
        options: ["L'Afrique", "L'Asie", "L'Amérique du Sud", "L'Océanie"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Kilimandjaro est un volcan isolé de Tanzanie qui domine la savane est-africaine.",
      },
    ],
  },

  "u3-n3": {
    quiz: {
      id: "u3-n3",
      creator_id: "system-path",
      title: "Déserts Inhospitaliers",
      description: "Explore les étendues arides du Sahara à l'Atacama.",
      category: "deserts",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 640,
      average_score: 70,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["deserts", "aridite", "sable", "parcours"],
    },
    questions: [
      {
        id: "u3-n3-q1",
        quiz_id: "u3-n3",
        question_text: "Quel désert d'Amérique du Sud est considéré comme le plus aride de la planète en dehors des pôles ?",
        question_type: "mcq",
        correct_answer: "Le désert d'Atacama",
        correct_answers: null,
        options: ["Le désert d'Atacama", "Le désert de Patagonie", "Le désert de Sechura", "Le désert de Sonora"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Atacama au Chili est si sec que certaines stations météo n'y ont jamais enregistré la moindre goutte de pluie.",
      },
      {
        id: "u3-n3-q2",
        quiz_id: "u3-n3",
        question_text: "Dans quels pays s'étend principalement le désert de Gobi, connu pour ses hivers glacials ?",
        question_type: "mcq",
        correct_answer: "La Mongolie et la Chine",
        correct_answers: null,
        options: ["La Mongolie et la Chine", "L'Inde et le Pakistan", "Le Kazakhstan et l'Ouzbékistan", "La Russie et la Mongolie"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le désert de Gobi s'étend sur 1,3 million de km² entre le sud de la Mongolie et le nord de la Chine.",
      },
      {
        id: "u3-n3-q3",
        quiz_id: "u3-n3",
        question_text: "Quel est le plus grand désert chaud du globe, couvrant une grande partie de l'Afrique du Nord ?",
        question_type: "mcq",
        correct_answer: "Le Sahara",
        correct_answers: null,
        options: ["Le Sahara", "Le Kalahari", "Le désert d'Arabie", "Le désert de Simpson"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Sahara s'étend sur plus de 9 millions de km² et traverse 11 pays africains.",
      },
      {
        id: "u3-n3-q4",
        quiz_id: "u3-n3",
        question_text: "Dans quel pays d'Afrique australe trouve-t-on le désert du Namib, bordant directement l'océan Atlantique ?",
        question_type: "mcq",
        correct_answer: "La Namibie",
        correct_answers: null,
        options: ["La Namibie", "Le Botswana", "L'Afrique du Sud", "Le Zimbabwe"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Namib est considéré comme le plus vieux désert du monde avec ses spectaculaires dunes rouges de Sossusvlei.",
      },
      {
        id: "u3-n3-q5",
        quiz_id: "u3-n3",
        question_text: "Quel est le plus grand désert de sel au monde, situé sur les hauts plateaux de Bolivie ?",
        question_type: "mcq",
        correct_answer: "Le Salar d'Uyuni",
        correct_answers: null,
        options: ["Le Salar d'Uyuni", "Le Grand Lac Salé", "Le Salar d'Atacama", "Le lac Natron"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Salar d'Uyuni s'étend sur plus de 10 500 km² à 3 650 m d'altitude et contient de gigantesques réserves de lithium.",
      },
    ],
  },

  "u3-boss": {
    quiz: {
      id: "u3-boss",
      creator_id: "system-path",
      title: "Défi Boss : Aventurier de l'Extrême",
      description: "L'épreuve ultime de géographie sauvage.",
      category: "extreme",
      is_public: true,
      is_global: true,
      difficulty: "hard",
      time_limit_seconds: 30,
      total_plays: 490,
      average_score: 65,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["extreme", "nature", "boss", "parcours"],
    },
    questions: [
      {
        id: "u3-boss-q1",
        quiz_id: "u3-boss",
        question_text: "Quel est l'endroit le plus profond connu dans les océans terrestres (-10 994 m) ?",
        question_type: "mcq",
        correct_answer: "La fosse des Mariannes",
        correct_answers: null,
        options: ["La fosse des Mariannes", "La fosse de Porto Rico", "La fosse de Java", "La fosse des Tonga"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le point Challenger Deep dans la fosse des Mariannes atteint près de 11 km de profondeur dans le Pacifique Nord-Ouest.",
      },
      {
        id: "u3-boss-q2",
        quiz_id: "u3-boss",
        question_text: "Quel lac sibérien est à la fois le plus vieux et le plus profond du monde (1 642 m) ?",
        question_type: "mcq",
        correct_answer: "Le lac Baïkal",
        correct_answers: null,
        options: ["Le lac Baïkal", "Le lac Supérieur", "Le lac Tanganyika", "La mer Caspienne"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le lac Baïkal en Russie contient à lui seul environ 20 % de l'eau douce de surface non gelée de la planète.",
      },
      {
        id: "u3-boss-q3",
        quiz_id: "u3-boss",
        question_text: "Sur quel fleuve se trouvent les spectaculaires chutes Victoria, à la frontière de la Zambie et du Zimbabwe ?",
        question_type: "mcq",
        correct_answer: "Le Zambèze",
        correct_answers: null,
        options: ["Le Zambèze", "Le Congo", "Le Niger", "Le Limpopo"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Appelées Mosi-oa-Tunya (la fumée qui gronde), les chutes Victoria tombent de plus de 100 mètres de hauteur sur 1,7 km de largeur.",
      },
      {
        id: "u3-boss-q4",
        quiz_id: "u3-boss",
        question_text: "Quelle mer fermée, bordée par la Jordanie et Israël, constitue le point le plus bas de la Terre sur les terres émergées (-430 m) ?",
        question_type: "mcq",
        correct_answer: "La mer Morte",
        correct_answers: null,
        options: ["La mer Morte", "La mer de Galilée", "La mer Rouge", "La mer Caspienne"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La mer Morte a une salinité d'environ 34 %, ce qui empêche tout organisme macroscopique d'y vivre mais permet aux nageurs de flotter naturellement.",
      },
      {
        id: "u3-boss-q5",
        quiz_id: "u3-boss",
        question_text: "Quelle mer intérieure d'Asie centrale a perdu plus de 90 % de son volume en quelques décennies à cause de détournements d'eau ?",
        question_type: "mcq",
        correct_answer: "La mer d'Aral",
        correct_answers: null,
        options: ["La mer d'Aral", "La mer Noire", "Le lac Balkhach", "Le lac Tchad"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le détournement des fleuves Amou-Daria et Syr-Daria pour la culture du coton soviétique a provoqué l'une des pires catastrophes environnementales du XXe siècle.",
      },
    ],
  },

  // ── UNITÉ 4 : Drapeaux & Îles Mystérieuses ────────────────────────────
  "u4-n1": {
    quiz: {
      id: "u4-n1",
      creator_id: "system-path",
      title: "Drapeaux à Motifs Rares",
      description: "Identifie les emblèmes et symboles insolites des drapeaux mondiaux.",
      category: "flags",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 580,
      average_score: 74,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["drapeaux", "symboles", "vexillologie", "parcours"],
    },
    questions: [
      {
        id: "u4-n1-q1",
        quiz_id: "u4-n1",
        question_text: "Quel pays du monde est le seul à posséder un drapeau national qui n'est pas un quadrilatère ?",
        question_type: "mcq",
        correct_answer: "Le Népal",
        correct_answers: null,
        options: ["Le Népal", "Le Bhoutan", "La Suisse", "Le Vatican"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le drapeau du Népal est composé de deux fanions triangulaires superposés avec un soleil et un croissant de lune.",
      },
      {
        id: "u4-n1-q2",
        quiz_id: "u4-n1",
        question_text: "Quel animal légendaire figure au centre du drapeau du Bhoutan, symbolisant le Royaume du Tonnerre ?",
        question_type: "mcq",
        correct_answer: "Un dragon blanc (Druk)",
        correct_answers: null,
        options: ["Un dragon blanc (Druk)", "Un tigre royal", "Un aigle bicéphale", "Un lion d'or"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le dragon blanc Druk tient des joyaux dans ses griffes symbolisant la richesse et la pureté du pays.",
      },
      {
        id: "u4-n1-q3",
        quiz_id: "u4-n1",
        question_text: "Quel arbre emblématique figure en vert au centre du drapeau du Liban ?",
        question_type: "mcq",
        correct_answer: "Le cèdre",
        correct_answers: null,
        options: ["Le cèdre", "L'olivier", "Le chêne", "Le palmier"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le cèdre du Liban est mentionné à maintes reprises dans l'histoire antique et symbolise l'éternité et la paix.",
      },
      {
        id: "u4-n1-q4",
        quiz_id: "u4-n1",
        question_text: "Quel oiseau exotique orne la moitié supérieure du drapeau de la Papouasie-Nouvelle-Guinée ?",
        question_type: "mcq",
        correct_answer: "L'oiseau de paradis",
        correct_answers: null,
        options: ["L'oiseau de paradis", "Le toucan", "Le kiwi", "L'aigle royal"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'oiseau de paradis raggiana doré en vol symbolise l'émergence de la nation papouasienne.",
      },
      {
        id: "u4-n1-q5",
        quiz_id: "u4-n1",
        question_text: "Combien d'étoiles composent la constellation de la Croix du Sud visible sur le drapeau du Brésil et de l'Australie ?",
        question_type: "mcq",
        correct_answer: "5 étoiles",
        correct_answers: null,
        options: ["5 étoiles", "7 étoiles", "3 étoiles", "9 étoiles"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La Croix du Sud comprend quatre étoiles principales brillantes et une cinquième plus petite (Epsilon Crucis).",
      },
    ],
  },

  "u4-n2": {
    quiz: {
      id: "u4-n2",
      creator_id: "system-path",
      title: "Archipels du Pacifique",
      description: "Mets le cap sur les archipels lointains et atolls d'Océanie.",
      category: "islands",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 510,
      average_score: 68,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["iles", "pacifique", "oceanie", "parcours"],
    },
    questions: [
      {
        id: "u4-n2-q1",
        quiz_id: "u4-n2",
        question_text: "Quelle est la capitale de l'archipel des Fidji dans le Pacifique Sud ?",
        question_type: "mcq",
        correct_answer: "Suva",
        correct_answers: null,
        options: ["Suva", "Nuku'alofa", "Apia", "Port-Vila"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Suva est située sur la côte sud-est de la principale île des Fidji, Viti Levu.",
      },
      {
        id: "u4-n2-q2",
        quiz_id: "u4-n2",
        question_text: "À quel pays d'Amérique du Sud appartient l'archipel volcanique des Galápagos ?",
        question_type: "mcq",
        correct_answer: "L'Équateur",
        correct_answers: null,
        options: ["L'Équateur", "Le Chili", "Le Pérou", "La Colombie"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Les îles Galápagos, situées à 1 000 km des côtes équatoriennes, ont inspiré la théorie de l'évolution de Charles Darwin.",
      },
      {
        id: "u4-n2-q3",
        quiz_id: "u4-n2",
        question_text: "À quel pays appartient l'île de Pâques (Rapa Nui), célèbre pour ses monumentales statues Moaï ?",
        question_type: "mcq",
        correct_answer: "Le Chili",
        correct_answers: null,
        options: ["Le Chili", "L'Argentine", "Le Royaume-Uni", "La France"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'île de Pâques a été annexée par le Chili en 1888 et se trouve à plus de 3 500 km des côtes sud-américaines.",
      },
      {
        id: "u4-n2-q4",
        quiz_id: "u4-n2",
        question_text: "Quelle est la plus grande île de la Polynésie française, abritant la capitale Papeete ?",
        question_type: "mcq",
        correct_answer: "Tahiti",
        correct_answers: null,
        options: ["Tahiti", "Bora-Bora", "Moorea", "Raiatea"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Tahiti est une île haute et volcanique de l'archipel de la Société, entourée de récifs coralliens.",
      },
      {
        id: "u4-n2-q5",
        quiz_id: "u4-n2",
        question_text: "Quelle est la capitale du Vanuatu, pays insulaire mélanésien de 83 îles ?",
        question_type: "mcq",
        correct_answer: "Port-Vila",
        correct_answers: null,
        options: ["Port-Vila", "Honiara", "Tarawa", "Palikir"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Port-Vila est située sur la côte sud-ouest de l'île d'Éfaté.",
      },
    ],
  },

  "u4-boss": {
    quiz: {
      id: "u4-boss",
      creator_id: "system-path",
      title: "Défi Boss : Maître Navigateur",
      description: "Le grand test final des explorateurs et capitaines.",
      category: "boss",
      is_public: true,
      is_global: true,
      difficulty: "hard",
      time_limit_seconds: 30,
      total_plays: 380,
      average_score: 64,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["navigation", "oceans", "boss", "parcours"],
    },
    questions: [
      {
        id: "u4-boss-q1",
        quiz_id: "u4-boss",
        question_text: "Quel célèbre explorateur portugais a découvert en 1520 le détroit reliant l'Atlantique et le Pacifique au sud du Chili ?",
        question_type: "mcq",
        correct_answer: "Fernand de Magellan",
        correct_answers: null,
        options: ["Fernand de Magellan", "Vasco de Gama", "Christophe Colomb", "Francis Drake"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le détroit de Magellan sépare la Patagonie continentale de la Terre de Feu et permit la première circumnavigation mondiale.",
      },
      {
        id: "u4-boss-q2",
        quiz_id: "u4-boss",
        question_text: "Quel cap redouté par les marins marque la pointe méridionale de l'archipel de la Terre de Feu en Amérique du Sud ?",
        question_type: "mcq",
        correct_answer: "Le cap Horn",
        correct_answers: null,
        options: ["Le cap Horn", "Le cap de Bonne-Espérance", "Le cap Leeuwin", "Le cap Finisterre"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le cap Horn est réputé pour ses tempêtes violentes et les vagues géantes du passage de Drake.",
      },
      {
        id: "u4-boss-q3",
        quiz_id: "u4-boss",
        question_text: "En quelle année le canal de Panama a-t-il été officiellement inauguré pour relier l'Atlantique au Pacifique ?",
        question_type: "mcq",
        correct_answer: "1914",
        correct_answers: null,
        options: ["1914", "1898", "1932", "1955"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le premier navire à traverser officiellement le canal de Panama fut le SS Ancon le 15 août 1914.",
      },
      {
        id: "u4-boss-q4",
        quiz_id: "u4-boss",
        question_text: "Quel méridien approximatif suit la ligne internationale de changement de date dans l'océan Pacifique ?",
        question_type: "mcq",
        correct_answer: "Le 180e méridien",
        correct_answers: null,
        options: ["Le 180e méridien", "Le méridien de Greenwich (0°)", "Le 90e méridien Ouest", "Le 45e méridien Est"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Franchir la ligne de changement de date d'est en ouest fait avancer d'une journée entière.",
      },
      {
        id: "u4-boss-q5",
        quiz_id: "u4-boss",
        question_text: "Quelle mer de l'Atlantique Nord est la seule mer du monde à ne posséder aucune frontière côtière terrestre ?",
        question_type: "mcq",
        correct_answer: "La mer des Sargasses",
        correct_answers: null,
        options: ["La mer des Sargasses", "La mer des Caraïbes", "La mer Baltique", "La mer Rouge"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 20,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "La mer des Sargasses est délimitée uniquement par le Gulf Stream et d'autres grands courants océaniques giratoires.",
      },
    ],
  },
};

/**
 * Récupère le bundle quiz + questions pour un nœud du parcours, ou null si non trouvé
 */
export function getPathNodeQuiz(nodeId: string): PathQuizBundle | null {
  if (PATH_QUIZZES[nodeId]) {
    return PATH_QUIZZES[nodeId];
  }

  // Fallback dynamique si le nœud n'a pas encore son entrée dédiée
  return {
    quiz: {
      id: nodeId,
      creator_id: "system-path",
      title: `Défi de l'Étape • ${nodeId.toUpperCase()}`,
      description: "Valide cette étape du parcours en répondant correctement aux questions géographiques !",
      category: "mixed",
      is_public: true,
      is_global: true,
      difficulty: "medium",
      time_limit_seconds: 30,
      total_plays: 350,
      average_score: 75,
      created_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
      is_reported: false,
      report_count: 0,
      cover_image_url: null,
      validation_status: "approved",
      pending_validation: false,
      randomize_questions: false,
      randomize_answers: true,
      language: "fr",
      quiz_type_id: null,
      tags: ["parcours", "geographie"],
    },
    questions: [
      {
        id: `${nodeId}-q1`,
        quiz_id: nodeId,
        question_text: "Quelle est la capitale de l'Australie ?",
        question_type: "mcq",
        correct_answer: "Canberra",
        correct_answers: null,
        options: ["Canberra", "Sydney", "Melbourne", "Brisbane"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 0,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Canberra a été choisie comme compromis entre les rivales Sydney et Melbourne.",
      },
      {
        id: `${nodeId}-q2`,
        quiz_id: nodeId,
        question_text: "Quel est le plus haut sommet du continent africain (5 895 m) ?",
        question_type: "mcq",
        correct_answer: "Le Kilimandjaro",
        correct_answers: null,
        options: ["Le Kilimandjaro", "Le mont Kenya", "Le mont Stanley", "Le Drakensberg"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 1,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le mont Kilimandjaro en Tanzanie est un volcan éteint couronné de neiges éternelles.",
      },
      {
        id: `${nodeId}-q3`,
        quiz_id: nodeId,
        question_text: "Quel est le plus grand désert chaud de la planète ?",
        question_type: "mcq",
        correct_answer: "Le Sahara",
        correct_answers: null,
        options: ["Le Sahara", "Le désert d'Arabie", "Le désert de Gobi", "Le Kalahari"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 2,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le Sahara s'étend sur plus de 9 millions de km² en Afrique du Nord.",
      },
      {
        id: `${nodeId}-q4`,
        quiz_id: nodeId,
        question_text: "Dans quel pays coule le fleuve Amazone, le plus grand fleuve du monde par son débit ?",
        question_type: "mcq",
        correct_answer: "Le Brésil",
        correct_answers: null,
        options: ["Le Brésil", "L'Argentine", "Le Mexique", "Le Chili"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 3,
        created_at: new Date().toISOString(),
        complement_if_wrong: "L'Amazone prend sa source dans les Andes péruviennes et traverse tout le nord du Brésil jusqu'à l'Atlantique.",
      },
      {
        id: `${nodeId}-q5`,
        quiz_id: nodeId,
        question_text: "Quel détroit sépare l'Asie (Russie) de l'Amérique du Nord (Alaska) ?",
        question_type: "mcq",
        correct_answer: "Le détroit de Béring",
        correct_answers: null,
        options: ["Le détroit de Béring", "Le détroit de Magellan", "Le détroit de Drake", "Le détroit de Cook"],
        map_data: null,
        image_url: null,
        option_images: null,
        randomize_options: true,
        points: 10,
        order_index: 4,
        created_at: new Date().toISOString(),
        complement_if_wrong: "Le détroit de Béring ne fait que 83 km de large entre le cap Dejnev en Russie et le cap Prince-de-Galles en Alaska.",
      },
    ],
  };
}
