/**
 * 🏔️ Données de Géographie Physique & Merveilles de la Terre
 * Couvre les fleuves, les sommets, les détroits et les merveilles de l'UNESCO.
 */

export interface PhysicalGeoItem {
  id: string;
  name: string;
  category: "rivers" | "mountains" | "straits" | "wonders";
  emoji: string;
  metric: string; // Ex: "6 650 km", "8 848 m"
  location: string; // Ex: "Afrique", "Népal / Chine"
  countries: string[]; // Ex: ["Égypte", "Soudan", "Ouganda"]
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  anecdote: string;
  photoUrl?: string;
}

export const PHYSICAL_GEO_ITEMS: PhysicalGeoItem[] = [
  // ── 1. GRANDS FLEUVES DU MONDE 🌊 ──
  {
    id: "river-nile",
    name: "Le Nil",
    category: "rivers",
    emoji: "🌊",
    metric: "6 650 km",
    location: "Afrique de l'Est & du Nord",
    countries: ["Égypte", "Soudan", "Soudan du Sud", "Éthiopie", "Ouganda"],
    question: "Dans quelle mer le Nil se jette-t-il par son célèbre delta ?",
    options: ["La Mer Rouge", "La Mer Méditerranée", "L'Océan Indien", "La Mer Noire"],
    correctIndex: 1,
    explanation: "Le Nil coule vers le nord depuis les Grands Lacs africains pour se jeter dans la mer Méditerranée au niveau d'Alexandrie.",
    anecdote: "Le Nil Blanc et le Nil Bleu se rejoignent à Khartoum, la capitale du Soudan, avant de traverser le Sahara.",
    photoUrl: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "river-amazon",
    name: "L'Amazone",
    category: "rivers",
    emoji: "🌿",
    metric: "6 992 km • 209 000 m³/s",
    location: "Amérique du Sud",
    countries: ["Brésil", "Pérou", "Colombie"],
    question: "Quel fleuve possède le plus grand débit d'eau au monde, représentant 20% de l'eau douce rejetée dans les océans ?",
    options: ["Le Nil", "Le Yangtsé", "L'Amazone", "Le Mississippi"],
    correctIndex: 2,
    explanation: "L'Amazone a un débit supérieur aux 7 fleuves suivants réunis ! À son embouchure, l'océan Atlantique est adouci sur plus de 150 km au large.",
    anecdote: "Il n'existe aucun pont qui traverse l'Amazone sur l'ensemble de son cours en raison de l'immensité de la forêt tropicale.",
    photoUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "river-danube",
    name: "Le Danube",
    category: "rivers",
    emoji: "🚢",
    metric: "2 850 km",
    location: "Europe Centrale & Orientale",
    countries: ["Allemagne", "Autriche", "Slovaquie", "Hongrie", "Croatie", "Serbie", "Roumanie", "Bulgarie", "Moldavie", "Ukraine"],
    question: "Combien de capitales européennes sont directement traversées par le Danube ?",
    options: ["2 capitales", "4 capitales", "6 capitales", "8 capitales"],
    correctIndex: 1,
    explanation: "Le Danube traverse 4 capitales : Vienne (Autriche), Bratislava (Slovaquie), Budapest (Hongrie) et Belgrade (Serbie). Un record mondial !",
    anecdote: "Il prend sa source dans la Forêt-Noire en Allemagne et se jette dans la Mer Noire par un delta classé à l'UNESCO.",
    photoUrl: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "river-yangtze",
    name: "Le Yangtsé (Fleuve Bleu)",
    category: "rivers",
    emoji: "🐉",
    metric: "6 300 km",
    location: "Chine",
    countries: ["Chine"],
    question: "Sur quel grand fleuve d'Asie a été érigé le monumental barrage des Trois-Gorges ?",
    options: ["Le Fleuve Jaune", "Le Yangtsé", "Le Mékong", "Le Gange"],
    correctIndex: 1,
    explanation: "Le Yangtsé est le plus long fleuve d'Asie et le 3e plus long du monde. Le barrage des Trois-Gorges est la plus grande centrale hydroélectrique du monde.",
    anecdote: "Son bassin abrite plus de 400 millions de personnes, soit un tiers de la population chinoise !",
  },
  {
    id: "river-mississippi",
    name: "Le Mississippi",
    category: "rivers",
    emoji: "🦅",
    metric: "3 766 km",
    location: "Amérique du Nord",
    countries: ["États-Unis"],
    question: "Dans quelle étendue d'eau le fleuve Mississippi se jette-t-il après avoir traversé les États-Unis du nord au sud ?",
    options: ["La Baie d'Hudson", "L'Océan Pacifique", "Le Golfe du Mexique", "La Mer des Caraïbes"],
    correctIndex: 2,
    explanation: "Le Mississippi prend sa source au lac Itasca (Minnesota) et termine sa course au sud de La Nouvelle-Orléans dans le Golfe du Mexique.",
    anecdote: "Avec son affluent le Missouri, il forme le 4e système fluvial le plus long de la planète (6 275 km).",
  },

  // ── 2. SOMMETS & MONTAGNES 🏔️ ──
  {
    id: "mountain-everest",
    name: "Le Mont Everest (Sagarmāthā)",
    category: "mountains",
    emoji: "🏔️",
    metric: "8 848,86 m",
    location: "Himalaya • Asie",
    countries: ["Népal", "Chine (Tibet)"],
    question: "Sur la frontière entre quels pays se dresse le sommet de l'Everest, toit du monde ?",
    options: ["Inde et Népal", "Népal et Chine", "Pakistan et Chine", "Bhoutan et Inde"],
    correctIndex: 1,
    explanation: "La crête sommitale de l'Everest marque la frontière internationale exacte entre le Népal et la région autonome du Tibet en Chine.",
    anecdote: "Son sommet grandit d'environ 4 millimètres par an sous la poussée tectonique continue de la plaque indienne contre l'Eurasie.",
    photoUrl: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "mountain-kilimanjaro",
    name: "Le Kilimandjaro",
    category: "mountains",
    emoji: "🦒",
    metric: "5 895 m",
    location: "Afrique de l'Est",
    countries: ["Tanzanie"],
    question: "Dans quel pays d'Afrique se situe le Kilimandjaro, point culminant du continent africain ?",
    options: ["Kenya", "Tanzanie", "Éthiopie", "Ouganda"],
    correctIndex: 1,
    explanation: "Le Kilimandjaro est un stratovolcan éteint situé au nord-est de la Tanzanie, célèbre pour ses neiges éternelles proches de l'équateur.",
    anecdote: "C'est la plus haute montagne isolée (non rattachée à une chaîne) de la planète, s'élevant à près de 5 000 mètres au-dessus des plaines environnantes.",
    photoUrl: "https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "mountain-mont-blanc",
    name: "Le Mont Blanc",
    category: "mountains",
    emoji: "❄️",
    metric: "4 807,8 m",
    location: "Alpes • Europe",
    countries: ["France", "Italie"],
    question: "Le Mont Blanc est le plus haut sommet des Alpes et d'Europe occidentale. Dans quel massif s'élève-t-il ?",
    options: ["Les Pyrénées", "Les Alpes", "Les Carpates", "L'Oural"],
    correctIndex: 1,
    explanation: "Le Mont Blanc culmine dans le massif du Mont-Blanc à 4 808 mètres, à cheval entre la Haute-Savoie (France) et la Vallée d'Aoste (Italie).",
    anecdote: "La première ascension a été réalisée le 8 août 1786 par Jacques Balmat et le docteur Michel Paccard.",
    photoUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "mountain-aconcagua",
    name: "L'Aconcagua",
    category: "mountains",
    emoji: "🦙",
    metric: "6 961 m",
    location: "Cordillère des Andes",
    countries: ["Argentine"],
    question: "Quel est le point culminant de toute l'Amérique et de l'hémisphère Sud ?",
    options: ["L'Aconcagua", "Le Denali", "Le Chimborazo", "Le Huascarán"],
    correctIndex: 0,
    explanation: "Situé en Argentine tout près de la frontière chilienne, l'Aconcagua est le plus haut sommet du monde en dehors du continent asiatique.",
    anecdote: "Il fait partie des célèbres 'Sept Sommets' (Seven Summits), les points culminants des sept continents terrestres.",
    photoUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
  },

  // ── 3. DÉTROITS & CANAUX STRATÉGIQUES 🚢 ──
  {
    id: "strait-gibraltar",
    name: "Le Détroit de Gibraltar",
    category: "straits",
    emoji: "🚢",
    metric: "14 km de large",
    location: "Europe / Afrique",
    countries: ["Espagne", "Maroc", "Royaume-Uni (Gibraltar)"],
    question: "Quelles sont les deux étendues d'eau reliées par le détroit de Gibraltar ?",
    options: [
      "La Mer Noire et la Méditerranée",
      "L'Océan Atlantique et la Méditerranée",
      "La Mer Rouge et l'Océan Indien",
      "La Mer du Nord et la Manche",
    ],
    correctIndex: 1,
    explanation: "Ce bras de mer de seulement 14 km de large sépare l'Espagne du Maroc et permet l'accès maritime de l'Atlantique à la mer Méditerranée.",
    anecdote: "Dans l'Antiquité, le rocher de Gibraltar et le mont Jbel Musa au Maroc étaient appelés les 'Colonnes d'Hercule'.",
    photoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "strait-bosphorus",
    name: "Le Détroit du Bosphore",
    category: "straits",
    emoji: "🕌",
    metric: "30 km de long",
    location: "Istanbul • Turquie",
    countries: ["Turquie"],
    question: "Quelle célèbre mégapole mondiale est coupée en deux par le détroit du Bosphore, à cheval sur l'Europe et l'Asie ?",
    options: ["Athènes", "Le Caire", "Istanbul", "Beyrouth"],
    correctIndex: 2,
    explanation: "Le Bosphore relie la mer Noire à la mer de Marmara et divise Istanbul en deux rives : la rive européenne et la rive asiatique.",
    anecdote: "C'est l'un des détroits les plus étroits utilisés pour la navigation internationale, avec seulement 700 mètres de large à son point le plus étroit.",
    photoUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "strait-suez",
    name: "Le Canal de Suez",
    category: "straits",
    emoji: "⚓",
    metric: "193 km de long",
    location: "Égypte",
    countries: ["Égypte"],
    question: "Inauguré en 1869, le canal de Suez permet aux navires de relier l'Europe à l'Asie sans contourner quel continent ?",
    options: ["L'Amérique du Sud", "L'Afrique", "L'Océanie", "L'Asie centrale"],
    correctIndex: 1,
    explanation: "Le canal de Suez relie Port-Saïd (Méditerranée) à Suez (mer Rouge), évitant aux navires un détour de 9 000 km autour de l'Afrique par le cap de Bonne-Espérance.",
    anecdote: "Environ 12% du commerce maritime mondial transite par ce passage stratégique chaque année.",
    photoUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "strait-panama",
    name: "Le Canal de Panama",
    category: "straits",
    emoji: "🌴",
    metric: "80 km • Système d'écluses",
    location: "Amérique Centrale",
    countries: ["Panama"],
    question: "Le canal de Panama traverse l'isthme de Panama pour relier quels deux océans ?",
    options: [
      "Atlantique et Arctique",
      "Pacifique et Indien",
      "Atlantique et Pacifique",
      "Méditerranée et Atlantique",
    ],
    correctIndex: 2,
    explanation: "Le canal permet de franchir les Amériques sans avoir à affronter les redoutables tempêtes du cap Horn tout au sud du Chili.",
    anecdote: "Les navires sont élevés à 26 mètres au-dessus du niveau de la mer par des écluses géantes pour traverser le lac Gatún avant d'être redescendus.",
    photoUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "strait-malacca",
    name: "Le Détroit de Malacca",
    category: "straits",
    emoji: "🌏",
    metric: "800 km de long",
    location: "Asie du Sud-Est",
    countries: ["Singapour", "Malaisie", "Indonésie"],
    question: "Quel détroit d'Asie du Sud-Est, situé entre l'Indonésie et la Malaisie, est le couloir maritime le plus fréquenté au monde ?",
    options: ["Le Détroit de Malacca", "Le Détroit d'Ormuz", "Le Détroit de Béring", "Le Détroit de Torrès"],
    correctIndex: 0,
    explanation: "Le détroit de Malacca relie l'océan Indien à la mer de Chine méridionale. Près d'un quart du pétrole mondial y transite.",
    anecdote: "La cité-État de Singapour doit une grande part de sa richesse exceptionnelle à sa position de vigie à l'entrée de ce détroit.",
    photoUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80",
  },

  // ── 4. MERVEILLES DU MONDE & UNESCO 🏛️ ──
  {
    id: "wonder-petra",
    name: "La Cité de Pétra",
    category: "wonders",
    emoji: "🏺",
    metric: "VIIIe siècle av. J.-C.",
    location: "Moyen-Orient",
    countries: ["Jordanie"],
    question: "Dans quel pays se trouve la cité antique de Pétra, taillée à même les falaises de grès rose ?",
    options: ["Jordanie", "Égypte", "Arabie Saoudite", "Liban"],
    correctIndex: 0,
    explanation: "Pétra était la capitale florissante du royaume des Nabatéens. Son monument le plus célèbre est la 'Khazneh' (Le Trésor).",
    anecdote: "La cité était cachée dans un étroit défilé rocheux (le Siq) et est restée inconnue du monde occidental jusqu'en 1812.",
    photoUrl: "https://images.unsplash.com/photo-1579606032834-deaff84a30e8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-machu-picchu",
    name: "Le Machu Picchu",
    category: "wonders",
    emoji: "🦙",
    metric: "2 430 m d'altitude",
    location: "Cordillère des Andes",
    countries: ["Pérou"],
    question: "Quelle civilisation précolombienne a bâti la cité sanctuaire perchée du Machu Picchu ?",
    options: ["Les Mayas", "Les Aztèques", "Les Incas", "Les Toltèques"],
    correctIndex: 2,
    explanation: "Érigé au XVe siècle sous l'empereur Pachacútec, le Machu Picchu est le chef-d'œuvre absolu de l'architecture et de l'ingénierie inca.",
    anecdote: "Les blocs de granit géants ont été taillés et emboîtés sans aucun mortier avec une telle précision qu'on ne peut pas y glisser une lame de couteau.",
    photoUrl: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-mariana-trench",
    name: "La Fosse des Mariannes",
    category: "wonders",
    emoji: "🌊",
    metric: "10 994 m de profondeur",
    location: "Océan Pacifique Nord-Ouest",
    countries: ["Îles Mariannes du Nord", "États-Unis", "Micronésie"],
    question: "Quelle est la profondeur maximale atteinte par le point le plus profond des océans terrestres, le gouffre Challenger dans la fosse des Mariannes ?",
    options: ["Près de 6 000 mètres", "Près de 8 500 mètres", "Près de 11 000 mètres", "Près de 15 000 mètres"],
    correctIndex: 2,
    explanation: "Le gouffre Challenger plonge à 10 994 mètres sous le niveau de la mer. Si on y déposait le mont Everest (8 848 m), son sommet serait encore immergé sous plus de 2 kilomètres d'eau !",
    anecdote: "La pression au fond de la fosse dépasse 1 000 bars, soit plus de mille fois la pression atmosphérique au niveau de la mer.",
    photoUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-angkor-wat",
    name: "Angkor Wat",
    category: "wonders",
    emoji: "🛕",
    metric: "162,6 hectares",
    location: "Asie du Sud-Est",
    countries: ["Cambodge"],
    question: "Dans quel pays d'Asie du Sud-Est se dresse le temple monumental d'Angkor Wat, plus grand monument religieux du monde ?",
    options: ["Thaïlande", "Cambodge", "Viêt Nam", "Laos"],
    correctIndex: 1,
    explanation: "Angkor Wat est le cœur de l'empire khmer du XIIe siècle. Sa silhouette à 5 tours orne fièrement le drapeau national du Cambodge.",
    anecdote: "Construit initialement comme temple hindou dédié à Vishnou, il est progressivement devenu un sanctuaire bouddhiste au fil des siècles.",
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-colosseum",
    name: "Le Colisée de Rome",
    category: "wonders",
    emoji: "🏛️",
    metric: "Ier siècle apr. J.-C. (70-80)",
    location: "Rome • Italie",
    countries: ["Italie"],
    question: "Combien de spectateurs le Colisée de Rome pouvait-il accueillir lors des combats de gladiateurs et spectacles navals ?",
    options: ["Environ 10 000", "Environ 25 000", "Entre 50 000 et 80 000", "Plus de 200 000"],
    correctIndex: 2,
    explanation: "Le Colisée (amphithéâtre Flavien) pouvait accueillir plus de 50 000 spectateurs grâce à un ingénieux réseau de 80 entrées et vomitoires.",
    anecdote: "L'arène pouvait être inondée pour reconstituer des batailles navales en temps réel (les naumachies).",
    photoUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-taj-mahal",
    name: "Le Taj Mahal",
    category: "wonders",
    emoji: "🕌",
    metric: "1632 - 1653",
    location: "Agra • Inde",
    countries: ["Inde"],
    question: "En hommage à qui l'empereur moghol Shah Jahan a-t-il fait construire le somptueux mausolée de marbre blanc du Taj Mahal ?",
    options: ["À sa mère", "À son épouse bien-aimée Mumtaz Mahal", "À son père", "À sa fille aînée"],
    correctIndex: 1,
    explanation: "Shah Jahan a érigé ce monument d'amour éternel après la mort de son épouse Mumtaz Mahal en donnant naissance à leur 14e enfant.",
    anecdote: "Le marbre blanc translucide change de couleur au fil de la journée : rosé à l'aube, blanc éblouissant à midi et doré sous la lune.",
    photoUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-grand-canyon",
    name: "Le Grand Canyon",
    category: "wonders",
    emoji: "🏜️",
    metric: "446 km de long • 1 800 m de profondeur",
    location: "Arizona • États-Unis",
    countries: ["États-Unis"],
    question: "Quel fleuve a creusé les gorges spectaculaires du Grand Canyon du Colorado au fil de millions d'années ?",
    options: ["Le Colorado", "Le Mississippi", "Le Rio Grande", "Le Columbia"],
    correctIndex: 0,
    explanation: "Le fleuve Colorado et ses affluents ont incisé le plateau du Colorado en exposant près de deux milliards d'années d'histoire géologique de la Terre.",
    anecdote: "La largeur du canyon varie de 800 mètres à plus de 29 kilomètres entre la rive nord et la rive sud.",
    photoUrl: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "wonder-victoria-falls",
    name: "Les Chutes Victoria",
    category: "wonders",
    emoji: "💧",
    metric: "1 708 m de large • 108 m de haut",
    location: "Afrique Australe",
    countries: ["Zambie", "Zimbabwe"],
    question: "Sur quel grand fleuve d'Afrique australe se déversent les gigantesques chutes Victoria (Mosi-oa-Tunya) ?",
    options: ["Le Zambèze", "Le Congo", "L'Orange", "Le Limpopo"],
    correctIndex: 0,
    explanation: "Le Zambèze plonge de plus de 100 mètres dans une gorge basaltique étroite, formant le plus grand rideau d'eau au monde.",
    anecdote: "Le nom indigène 'Mosi-oa-Tunya' signifie 'La fumée qui gronde' : la colonne de brume s'élève à plus de 400 mètres et est visible à 50 km à la ronde.",
    photoUrl: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=1200&q=80",
  },
];
